#!/bin/csh

foreach prog (CombiFrame NoLayout TestButton RectFrame CircleFrame)
echo compiling $prog
javac $prog.java
echo running $prog
java $prog
echo "-------------------------"
#echo 次のプログラムを実行するには enter を押して下さい．
# bash -c read
end
